-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 5fe82b3a37983b3270b7afa2ed80b90b158f3a7c
    hooks:
    -   id: trailing-whitespace
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer

-   repo: git://github.com/FalconSocial/pre-commit-python-sorter
    sha: 1.0.1
    hooks:
    -   id: python-import-sorter
        args: ['--silent-overwrite']
